### ISSUE TITLE
Question about the Relative Depth

### ISSUE THREAD

**Issue by chuong98** [hustvl/SparseTrack#1]
Hi, thanks for releasing the code. It is an interesting paper.
I have questions about the Equ(1) in your paper:
1. `Lp = sqrt((xp − xd)^2 +  (yp − yd)^2)`
but since xD=xp, and yd=0 by the definition of point D, then isn't Lp=yp always?
2. The lower body parts are often occluded in the scene, thus the approximation of Lp may no longer acceptable.
Thank you

**Comment by Xavier-Lin** [comment]
Thank you for your interest in SparseTrack. There are two main points that need clarification: 1) The variable "yd" actually equals the height (h) of the image. To accommodate cases where the bounding box extends beyond the image boundaries, we typically set yd to 2000. 2) The second question is an excellent one. Due to the influence of Kalman filtering, the shape of the occluded targets' lower body is preserved within a certain range. Additionally, CrowdHuman dataset contains a significant number of instances with occluded lower bodies. The YOLOX detector has been extensively trained on datasets like CrowdHuman to ensure robustness in detecting occluded targets.

**Comment by Xavier-Lin** [comment]
If you have no further questions or suggestions, we will consider closing this issue. Thank you very much for your attention.

**Comment by tteresi7** [comment]
> Due to the influence of Kalman filtering, the shape of the occluded targets' lower body is preserved within a certain range.

I just want to chip in on this, this is only true if you're using the Kalman filter outputs as the truth.  In reality we're matching to detections which will not include the occlusions, so it will not be preserved.
